export const PROJECT_DEFAULT_PAGE = 1;
export const PROJECT_DEFAULT_LIMIT = 20;
export const PROJECT_MAX_LIMIT = 100;
export const PROJECT_MAX_NAME_LENGTH = 160;
export const PROJECT_MAX_DESCRIPTION_LENGTH = 5_000;
export const PROJECT_MAX_LANGUAGE_LENGTH = 80;
