apiVersion: v1
kind: ConfigMap
metadata:
  name: reviewsha-config
  namespace: reviewsha
data:
  NODE_ENV: production
  API_PORT: '3000'
  API_PREFIX: api/v1
  REDIS_URL: redis://redis.example.internal:6379
  MINIO_ENDPOINT: https://object.example.com
